addpath required_toolboxes/1_do_hmm_estimations/
addpath required_toolboxes/2_AIC_Criterion/scripts/
addpath required_toolboxes/3_Check_Consistency/
addpath(genpath('required_toolboxes/HMM-MAR/'));
addpath(genpath('required_toolboxes/RainCloudPlots/'))
addpath(genpath('required_toolboxes/NBS/NBSDirected1.0.1/'))
load required_toolboxes/is_ie_melancholic.txt



% load in the timeseries generated by ROI extraction:
% the 10 = start from volume 10.
% the 1445 = this is the length needed.
% the scanner takes more scans, but the movie had already ended. do not
% include these scans.
[mat, t] = prepare_hmm('timeseries/ts*.txt', 10, 1445);


% run the HMM, using 2, 4, 6, ...., 24 states. Do 5 repetitions for each
% one.
run_the_hmm(mat, t, 'positive_network', [2:2:24], 5);

% to check the AIC criterion, use a script from another toolbox, which is
% in: required_toolboxes/2_AIC_Criterion/scripts/
% it is called: make_AIC_figure.m
% change to your own needs.


% if we have 12 states, we can run the HMM again to get 25 inferences
run_the_hmm(mat, t, 'positive_network', [12], 25);

% we need to pick the 'most consistent' inference, compared to other
% inferences:
post_hmm_6_check_consistencies('positive_network', 12);


% the figure should help you to choose a file, this file contains the
% inference to be used from now on.
this_file = 'positive_network/HMMrun_K10_rep_17.mat';


% do the quick assessment of the state configurations:
post_hmm_2b_make_state_quickly(this_file, 'Positive_Network_III_regions.txt');
% post_hmm_2_make_state_figures(this_file, 'Positive_Network_III_regions.txt');



% make viterbi path figures, for 'nonmel', and 'mel' samples:
post_hmm_3_make_vpath_figures(this_file,find(is_ie_melancholic==0), 1, 'nonmel');
post_hmm_3_make_vpath_figures(this_file,find(is_ie_melancholic==1), 1, 'mel');


% check out the FO, lifetimes, intervals ,and switching rates too:
post_hmm_5_make_stats_figures(this_file, 'FO',  is_ie_melancholic, {'MEL','NONMEL'})
post_hmm_5_make_stats_figures(this_file, 'lifetimes',  is_ie_melancholic, {'MEL','NONMEL'})
post_hmm_5_make_stats_figures(this_file, 'intervals',  is_ie_melancholic, {'MEL','NONMEL'})
post_hmm_5_make_stats_figures(this_file, 'switchingRate',  is_ie_melancholic, {'MEL','NONMEL'})

     
post_hmm_7_prepare_NBS_stats(this_file, is_ie_melancholic)



% check these things again, for periods where the movie is 'positive':

% pos_mask_old = load('../7_positive_network_III/annotations/Scenes_Positive_mask.txt');pos_mask_old(1446:end) = []; pos_mask_old(1:10) = [];
pos_mask = load('temporal_masksScenes_Positive_mask.txt');pos_mask(1446:end) = []; pos_mask(1:10) = [];



% make things plot with the pos_mask...
post_hmm_3_make_vpath_figures(this_file,find(is_ie_melancholic==0), 1, 'nonmel', pos_mask);
post_hmm_3_make_vpath_figures(this_file,find(is_ie_melancholic==1), 1, 'mel', pos_mask);

% mask to put onto the vpath before calculatingthe
post_hmm_5_make_stats_figures(this_file, 'FO',            is_ie_melancholic, {'MEL','NONMEL'}, 1, pos_mask)
post_hmm_5_make_stats_figures(this_file, 'lifetimes',     is_ie_melancholic, {'MEL','NONMEL'}, 1, pos_mask)
post_hmm_5_make_stats_figures(this_file, 'intervals',     is_ie_melancholic, {'MEL','NONMEL'}, 1, pos_mask)
post_hmm_5_make_stats_figures(this_file, 'switchingRate', is_ie_melancholic, {'MEL','NONMEL'}, 1, pos_mask)


